name: Deploy to Development

on:
  push:
    branches: [dev]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Build for Development
        run: |
          echo "VITE_DEPLOY_TARGET=development" > .env.production
          echo "VITE_ROUTER_BASE=/portfolio-react" >> .env.production
          npm run build

      - name: Add noindex for SEO
        run: |
          # Add robots.txt to prevent indexing (dev environment)
          echo "User-agent: *" > dist/robots.txt
          echo "Disallow: /" >> dist/robots.txt

          # Update base href for GitHub Pages
          sed -i 's|<base href="/" />|<base href="/portfolio-react/" />|g' dist/index.html

          # Add noindex meta tag for development
          sed -i 's|<meta name="viewport"|<meta name="robots" content="noindex, nofollow" />\n    <meta name="viewport"|g' dist/index.html

      - name: Deploy to gh-pages-dev
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages-dev
          force_orphan: true
          commit_message: 'Deploy to development from dev branch'
